version: 2

models:
  - name: int_customer_orders
    description: Intermediate model joining customers with their sales orders. Includes derived fields such as order channel, status descriptions, shipping metrics, and discount calculations. Uses surrogate keys for unique identification.
    columns:
      - name: customer_order_key
        description: Surrogate key combining customer_id and sales_order_id for unique identification
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customer. References stg_customers.
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: first_name
        description: Customer first name
      - name: last_name
        description: Customer last name
      - name: territory_id
        description: Sales territory identifier
      - name: store_id
        description: Store identifier
      - name: sales_order_id
        description: Foreign key to sales order. References stg_sales_orders.
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales_orders')
              field: sales_order_id
      - name: order_date
        description: Date when the order was placed
        tests:
          - not_null
      - name: due_date
        description: Date when the order is due
      - name: ship_date
        description: Date when the order was shipped
      - name: status
        description: Order status code (1-6)
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]
      - name: order_channel
        description: Derived field indicating order channel (Online/Offline)
        tests:
          - not_null
          - accepted_values:
              values: ['Online', 'Offline']
      - name: order_status_description
        description: Derived field with human-readable order status description
        tests:
          - not_null
          - accepted_values:
              values: ['In Process', 'Approved', 'Backordered', 'Rejected', 'Shipped', 'Cancelled', 'Unknown']
      - name: days_to_ship
        description: Derived field calculating days between order date and ship date
      - name: days_until_due
        description: Derived field calculating days between order date and due date
      - name: order_detail_id
        description: Order detail identifier
        tests:
          - not_null
      - name: product_id
        description: Product identifier
        tests:
          - not_null
      - name: order_qty
        description: Quantity ordered
        tests:
          - not_null
      - name: unit_price
        description: Unit price of the product
        tests:
          - not_null
      - name: unit_price_discount
        description: Discount amount per unit
      - name: line_total
        description: Total amount for this line item
        tests:
          - not_null
      - name: discount_percentage
        description: Derived field calculating discount as percentage of unit price
      - name: net_amount
        description: Net amount after discount (same as line_total)
        tests:
          - not_null
      - name: gross_amount
        description: Derived field calculating gross amount before discount (unit_price * order_qty)
        tests:
          - not_null
      - name: total_discount_amount
        description: Derived field calculating total discount amount (unit_price_discount * order_qty)

  - name: int_product_sales
    description: Intermediate model joining products with their sales orders. Includes derived fields such as profit margins, discount calculations, price comparisons, and product availability status. Uses surrogate keys for unique identification.
    columns:
      - name: product_sale_key
        description: Surrogate key combining product_id and order_detail_id for unique identification
        tests:
          - unique
          - not_null
      - name: product_id
        description: Foreign key to product. References stg_products.
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: product_name
        description: Product name
      - name: product_number
        description: Unique product number
      - name: color
        description: Product color
      - name: size
        description: Product size
      - name: product_line
        description: Product line category
      - name: product_class
        description: Product class category
      - name: product_style
        description: Product style category
      - name: product_subcategory_id
        description: Product subcategory identifier
      - name: subcategory_name
        description: Product subcategory name
      - name: product_category_id
        description: Product category identifier
      - name: list_price
        description: Product list price
      - name: standard_cost
        description: Product standard cost
      - name: make_flag
        description: Flag indicating if product is manufactured
      - name: finished_goods_flag
        description: Flag indicating if product is a finished good
      - name: sales_order_id
        description: Sales order identifier
        tests:
          - not_null
      - name: order_date
        description: Date when the order was placed
        tests:
          - not_null
      - name: order_detail_id
        description: Order detail identifier
        tests:
          - not_null
      - name: order_qty
        description: Quantity ordered
        tests:
          - not_null
      - name: unit_price
        description: Unit price of the product
        tests:
          - not_null
      - name: unit_price_discount
        description: Discount amount per unit
      - name: line_total
        description: Total amount for this line item
        tests:
          - not_null
      - name: profit_margin_percentage
        description: Derived field calculating profit margin as percentage ((unit_price - standard_cost) / standard_cost * 100)
      - name: profit_amount
        description: Derived field calculating total profit amount ((unit_price - standard_cost) * order_qty)
      - name: discount_percentage
        description: Derived field calculating discount as percentage of unit price
      - name: price_difference_from_list
        description: Derived field calculating difference between unit price and list price
      - name: price_ratio_to_list
        description: Derived field calculating ratio of unit price to list price
      - name: product_availability_status
        description: Derived field indicating product availability status (Available, Discontinued, Ended, Not Yet Available)
        tests:
          - not_null
          - accepted_values:
              values: ['Available', 'Discontinued', 'Ended', 'Not Yet Available']
      - name: is_current_product
        description: Derived field indicating if product is currently available (1) or not (0)
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]

