version: 2

models:
  - name: fct_customer_metrics
    description: Business-ready mart model providing comprehensive customer metrics and KPIs. Aggregates customer order data to provide insights into customer behavior, purchasing patterns, revenue, and engagement metrics.
    columns:
      - name: customer_id
        description: Primary key for customers. References stg_customers.
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: first_name
        description: Customer first name
      - name: last_name
        description: Customer last name
      - name: territory_id
        description: Sales territory identifier
      - name: store_id
        description: Store identifier
      - name: total_orders
        description: KPI - Total number of distinct orders placed by customer
        tests:
          - not_null
      - name: total_order_items
        description: KPI - Total number of order line items across all orders
        tests:
          - not_null
      - name: online_orders
        description: KPI - Number of orders placed online
        tests:
          - not_null
      - name: offline_orders
        description: KPI - Number of orders placed offline
        tests:
          - not_null
      - name: first_order_date
        description: Date of customer's first order
        tests:
          - not_null
      - name: last_order_date
        description: Date of customer's most recent order
        tests:
          - not_null
      - name: customer_lifetime_days
        description: KPI - Number of days between first and last order (customer lifetime)
      - name: total_revenue
        description: KPI - Total revenue generated from customer (sum of line totals)
        tests:
          - not_null
      - name: total_gross_revenue
        description: KPI - Total gross revenue before discounts
        tests:
          - not_null
      - name: total_discounts
        description: KPI - Total discount amount given to customer
        tests:
          - not_null
      - name: avg_order_value
        description: KPI - Average value per order line item
      - name: avg_order_amount
        description: KPI - Average total amount per order
      - name: total_quantity_ordered
        description: KPI - Total quantity of products ordered
        tests:
          - not_null
      - name: avg_quantity_per_item
        description: Average quantity per order line item
      - name: avg_discount_percentage
        description: Average discount percentage applied to customer orders
      - name: items_with_discount
        description: Number of order items that received a discount
        tests:
          - not_null
      - name: avg_days_to_ship
        description: KPI - Average number of days to ship orders
      - name: max_days_to_ship
        description: Maximum number of days to ship an order
      - name: min_days_to_ship
        description: Minimum number of days to ship an order
      - name: shipped_orders
        description: KPI - Number of orders that were shipped
        tests:
          - not_null
      - name: cancelled_orders
        description: KPI - Number of orders that were cancelled
        tests:
          - not_null
      - name: in_process_orders
        description: KPI - Number of orders currently in process
        tests:
          - not_null
      - name: unique_products_purchased
        description: KPI - Number of distinct products purchased by customer
        tests:
          - not_null

  - name: fct_product_performance
    description: Business-ready mart model providing comprehensive product performance metrics and KPIs. Aggregates product sales data to provide insights into product sales, revenue, profitability, and market performance.
    columns:
      - name: product_id
        description: Primary key for products. References stg_products.
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: product_name
        description: Product name
      - name: product_number
        description: Unique product number
      - name: color
        description: Product color
      - name: size
        description: Product size
      - name: product_line
        description: Product line category
      - name: product_class
        description: Product class category
      - name: product_style
        description: Product style category
      - name: product_subcategory_id
        description: Product subcategory identifier
      - name: subcategory_name
        description: Product subcategory name
      - name: product_category_id
        description: Product category identifier
      - name: list_price
        description: Product list price
      - name: standard_cost
        description: Product standard cost
      - name: make_flag
        description: Flag indicating if product is manufactured
      - name: finished_goods_flag
        description: Flag indicating if product is a finished good
      - name: product_availability_status
        description: Product availability status
      - name: is_current_product
        description: Flag indicating if product is currently available
      - name: total_orders
        description: KPI - Total number of distinct orders containing this product
        tests:
          - not_null
      - name: total_sales_items
        description: KPI - Total number of times this product was sold (order line items)
        tests:
          - not_null
      - name: first_sale_date
        description: Date of first sale of this product
        tests:
          - not_null
      - name: last_sale_date
        description: Date of most recent sale of this product
        tests:
          - not_null
      - name: sales_period_days
        description: Number of days between first and last sale
      - name: total_revenue
        description: KPI - Total revenue generated from this product
        tests:
          - not_null
      - name: total_gross_revenue
        description: KPI - Total gross revenue before discounts
        tests:
          - not_null
      - name: total_discounts
        description: KPI - Total discount amount given on this product
        tests:
          - not_null
      - name: avg_selling_price
        description: KPI - Average selling price of the product
      - name: min_selling_price
        description: Minimum selling price of the product
      - name: max_selling_price
        description: Maximum selling price of the product
      - name: total_quantity_sold
        description: KPI - Total quantity of product sold
        tests:
          - not_null
      - name: avg_quantity_per_order
        description: Average quantity sold per order
      - name: min_quantity_sold
        description: Minimum quantity sold in a single order
      - name: max_quantity_sold
        description: Maximum quantity sold in a single order
      - name: total_profit
        description: KPI - Total profit generated from this product
      - name: avg_profit_margin_percentage
        description: KPI - Average profit margin percentage
      - name: min_profit_margin_percentage
        description: Minimum profit margin percentage
      - name: max_profit_margin_percentage
        description: Maximum profit margin percentage
      - name: avg_price_difference_from_list
        description: Average difference between selling price and list price
      - name: avg_price_ratio_to_list
        description: Average ratio of selling price to list price
      - name: avg_discount_percentage
        description: Average discount percentage applied to this product
      - name: avg_price_to_list_ratio
        description: Average price to list price ratio
      - name: revenue_per_unit
        description: KPI - Revenue generated per unit sold
      - name: profit_per_unit
        description: KPI - Profit generated per unit sold

