version: 2

models:
  - name: stg_customers
    description: Staging model for customer data with basic cleaning applied. Extracts from Customer and Person tables, applies trimming and case normalization, removes null IDs.
    columns:
      - name: customer_id
        description: Primary key for customers. Cast to integer, null values removed.
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer first name. Trimmed and converted to uppercase.
      - name: last_name
        description: Customer last name. Trimmed and converted to uppercase.
      - name: email_promotion
        description: Email promotion preference. Trimmed and converted to lowercase.
      - name: store_id
        description: Store identifier where customer is associated. Cast to integer.
      - name: territory_id
        description: Sales territory identifier. Cast to integer.
      - name: person_id
        description: Foreign key to person table. Cast to integer, null values removed.
        tests:
          - not_null
      - name: last_modified_date
        description: Last modified timestamp. Cast to datetime.
        tests:
          - not_null

  - name: stg_products
    description: Staging model for product data with basic cleaning applied. Extracts from Product and ProductSubcategory tables, applies trimming, case normalization, and type casting.
    columns:
      - name: product_id
        description: Primary key for products. Cast to integer, null values removed.
        tests:
          - unique
          - not_null
      - name: product_name
        description: Product name. Trimmed and converted to uppercase.
      - name: product_number
        description: Unique product number. Trimmed and converted to uppercase.
      - name: color
        description: Product color. Trimmed and converted to uppercase.
      - name: size
        description: Product size. Trimmed and converted to uppercase.
      - name: make_flag
        description: Flag indicating if product is manufactured. Cast to bit.
      - name: finished_goods_flag
        description: Flag indicating if product is a finished good. Cast to bit.
      - name: safety_stock_level
        description: Minimum stock level for safety. Cast to integer.
      - name: reorder_point
        description: Stock level at which to reorder. Cast to integer.
      - name: standard_cost
        description: Standard cost of the product. Cast to decimal(19,4).
      - name: list_price
        description: List price of the product. Cast to decimal(19,4).
      - name: product_line
        description: Product line category. Trimmed and converted to uppercase.
      - name: product_class
        description: Product class category. Trimmed and converted to uppercase.
      - name: product_style
        description: Product style category. Trimmed and converted to uppercase.
      - name: product_subcategory_id
        description: Foreign key to product subcategory. Cast to integer.
      - name: subcategory_name
        description: Name of the product subcategory. Trimmed and converted to uppercase.
      - name: product_category_id
        description: Foreign key to product category. Cast to integer.
      - name: sell_start_date
        description: Date when product became available for sale. Cast to date.
      - name: sell_end_date
        description: Date when product stopped being available for sale. Cast to date.
      - name: discontinued_date
        description: Date when product was discontinued. Cast to date.
      - name: last_modified_date
        description: Last modified timestamp. Cast to datetime.
        tests:
          - not_null

  - name: stg_sales_orders
    description: Staging model for sales order data with basic cleaning applied. Combines SalesOrderHeader and SalesOrderDetail tables, applies trimming, case normalization, type casting, and removes null IDs.
    columns:
      - name: sales_order_id
        description: Primary key for sales orders. Cast to integer, null values removed.
        tests:
          - unique
          - not_null
      - name: order_detail_id
        description: Primary key for order details. Cast to integer, null values removed.
        tests:
          - unique
          - not_null
      - name: order_date
        description: Date when the order was placed. Cast to date.
        tests:
          - not_null
      - name: due_date
        description: Date when the order is due. Cast to date.
      - name: ship_date
        description: Date when the order was shipped. Cast to date.
      - name: status
        description: Current status of the order. Cast to tinyint.
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]
      - name: online_order_flag
        description: Flag indicating if the order was placed online. Cast to bit.
      - name: sales_order_number
        description: Unique sales order number. Trimmed and converted to uppercase.
        tests:
          - unique
          - not_null
      - name: purchase_order_number
        description: Customer purchase order number. Trimmed and converted to uppercase.
      - name: customer_id
        description: Foreign key reference to customer. Cast to integer, null values removed.
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: sales_person_id
        description: ID of the sales person. Cast to integer.
      - name: territory_id
        description: Sales territory ID. Cast to integer.
      - name: product_id
        description: Foreign key reference to product. Cast to integer, null values removed.
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: order_qty
        description: Quantity ordered. Cast to smallint.
        tests:
          - not_null
      - name: unit_price
        description: Unit price of the product. Cast to decimal(19,4).
        tests:
          - not_null
      - name: unit_price_discount
        description: Discount amount per unit. Cast to decimal(19,4).
      - name: line_total
        description: Total amount for this line item. Cast to decimal(38,6).
        tests:
          - not_null
      - name: last_modified_date
        description: Last modified timestamp. Cast to datetime.
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sales_order_id
            - order_detail_id

